---
name: Repository Update

# yamllint disable-line rule:truthy
on:
  repository_dispatch:
    types: ["update"]

jobs:
  workflows:
    uses: coostax/ghactions-workflows/.github/workflows/repository-updater.yaml@main
    secrets:
      UPDATER_TOKEN: ${{ secrets.UPDATER_TOKEN }}
